### ISSUE TITLE
Add Markdown support for `message` and `note` fields.

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep-vscode#463]
Right now, the `note` and `message` fields from a YAML rule seem to be rendered as code blocks with a monospace font. For example:

<img width="894" alt="Image" src="https://github.com/user-attachments/assets/ced19b5e-1b5f-4ea3-bde4-e6fc33fa03e2" />

When writing rules on my team, I like to add context with code examples to the `note` field so that new devs have the context for why the rule exists, and so they know what to do to resolve it (we're not adding auto-fixed rules yet). The monospace font inside the popover when you hover over the rule breakage makes it kind of hard to read.

ESLint and TypeScript both support Markdown syntax for rendering doc strings on hover. It would be really nice if the ast-grep extension supported the same. Specifically:

- Basic code syntax highlighting (like \`\`\`ts)
- Bolding and italics
- Markdown link support (we often need to link to docs, and showing the full URL is very annoying).

**Comment by HerringtonDarkholme** [comment]
Wow Maria from Neovim supported in LSP 3.18 https://github.com/microsoft/language-server-protocol/pull/1905

**Comment by samwightt** [comment]
Oh that makes a lot more sense, thanks for the context on this! Realizing now that I have never seen this as a feature in ESLint 😅

**Comment by HerringtonDarkholme** [comment]
I'm thinking about showing `note` in hover request instead of `message` field.

`Note` is usually long and verbose to provide extra context. However, error message is shown in the problem panel and should be concise. 

<img width="536" alt="Image" src="https://github.com/user-attachments/assets/cd632552-30f5-4943-9440-d79a876a71a8" />

**Comment by samwightt** [comment]
Yeeeep definitely agree with this.  Note is helpful in the hover, but in the problems list it gets very long. I can sometimes have notes that are 2-3 paragraphs long (dense) to explain something like what a particular RxJS method does, links to docs, etc. Makes it very hard to scroll through issues panel at a glance.

**Comment by HerringtonDarkholme** [comment]
@samwightt, would you like to share an example rule? A real rule is better for testing so that the LSP response can be tweaked toward real usage instead of contrived mock text.

**Comment by samwightt** [comment]
Sure, here's one. Angular components have inputs and there's two ways of representing them:

```ts
@Input() something: Something
```

```ts
something = input<Something>();
```

There's an issue using the old decorator-based approach because that component input by default is not required. In order to make it required (and throw an error during build and usage) you have to do `@Input({ required: true })`. If you're not, the input is optional, which means that it could be `undefined`.

Most of the inputs in our codebase don't correctly set the type as `Something | undefined` for these inputs, leading to possible issues that `strictNullChecks` is not able to get. So I wrote this rule that explains this:

```yml
id: incorrect-optional-input-type
language: TypeScript
message: This input is optional, but the type for it does not include undefined.
severity: error
note: |
  Component inputs specified using the `@Input` decorator are optional by default.
  If they are not passed a value when used, they are passed `undefined`. To make them
  required, you set `@Input({ required: true })`.

  This rule is triggered if you do not specify the TS type correctly, do not provide
  a default value, or do not mark the input as required.

  To fix:

  - Add `| undefined` to the type of the input.
  - Add a default value to the input.
  - Make the input required.
  - Use the input signals API.
rule:
  any:
    - pattern: '@Input()'
    - pattern: '@Input($$$_)'
  not:
    has:
      kind: pair
      all:
        - has:
            field: key
            regex: required
        - has:
            kind: 'true'
      stopBy: end
  inside:
    kind: public_field_definition
    all:
      - not:
          has:
            field: value
            pattern: '$_'
      - has:
          kind: type_annotation
          not:
            has:
              kind: 'undefined'
              stopBy: end
```

These messages can get a bit long in the problems list in VSCode cause of the presence of the note field.
